application:
  host: 0.0.0.0
  port: 8000
database:
  host: "ep-bold-wildflower-a2dso7rn.eu-central-1.pg.koyeb.app"
  port: 5432
  username: "koyeb-adm"
  password: "npg_eIScEADZv3m5"
  database_name: "koyebdb"
